### ISSUE TITLE
Metrics - Distribution - Cooking Class

### ISSUE THREAD

**Issue by nevern02** [rubyforgood/growhaus_stats#10]
As a user, I want to record metrics for cooking classes entitled “Cosechando Salud”.  

A weekly metric is the Number of Families Served, classified as: “Zone 1” or “Outside”.  The sum of Zone 1 and Outside families should be the Total Families Served.  There is an additional subdivision, Mobile.  The number of those is not included in the count of Total Families.

**Comment by adunkman** [comment]
Implemented using [Google Forms](https://vt.tumblr.com/tumblr_nplmyoSCT01uvnik9_480.mp4).
