### ISSUE TITLE
Metrics - Production - Farm

### ISSUE THREAD

**Issue by nevern02** [rubyforgood/growhaus_stats#12]
As a user, I want to record metrics for the Hydroponic Farm entitled “Hidro Huerto”.

A weekly metric is the Number of Seedlings Harvested, classified by Type (Bibb, Asian Greens, Kale, Flowers & Herbs, and Other).  The sum of all types other than Flowers & Herbs is the Total. 

A monthly metric is Revenue generated by the farm.

**Comment by adunkman** [comment]
Google Forms’d.
