### ISSUE TITLE
Metrics - Education - Events

### ISSUE THREAD

**Issue by nevern02** [rubyforgood/growhaus_stats#13]
As a user, I want to record weekly metrics for Education.

A week can have multiple entries.  Each entry has the following fields: Type, Number of Participants, and Comments.

Each entry is associated with a number of Hours.  The Hours may be classified as: Zone 1-2, or Zone 3.  The sum of all hours for the entry is the Total Hours.

**Comment by adunkman** [comment]
Google Forms’d.
