### ISSUE TITLE
Metrics - Education - CRUD Types

### ISSUE THREAD

**Issue by nevern02** [rubyforgood/growhaus_stats#14]
As a user, when I create an entry for educational metrics, I want to select the Type from a list of available options.

As a user, I want to create, edit, and delete Types.

As a user, before I’ve created any custom Types, the following Types should be pre-populated when I’m creating metrics: Cosechando Salud, Food Boxes, Service Learning, Internship Program, Volunteer Days, Special Event, Other.

**Comment by adunkman** [comment]
Google Forms’d.
