### ISSUE TITLE
Metrics - Distribution - Food Boxes

### ISSUE THREAD

**Issue by nevern02** [rubyforgood/growhaus_stats#9]
As a user, I want to record metrics for Food Boxes.

A weekly metric is the Number of Boxes, classified by: Zone (1, 2, or 3) and Type.  The current types are “Basic”, “Family”, and “Neighborhood”, but those types are expected to change.  Therefore, the Type should be something that I can enter myself rather than a selectable list.  The sum of the zone boxes should equal the sum of the type boxes.  That sum should be the Total Boxes.

A monthly metric is Revenue generated by food boxes.

**Comment by adunkman** [comment]
Implemented using [Google Forms](https://38.media.tumblr.com/3ac47fb312b7b969581a8790b2149d9b/tumblr_inline_n07w590VHh1rxlfzd.jpg).
